# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Film.create(tittle:'Batman: The Dark King', synopsis:'Batman tiene que mantener el equilibrio entre el heroísmo y el vigilantismo para pelear contra un vil criminal conocido como el Guasón, que pretende sumir Ciudad Gótica en la anarquía.', image:'https://i.pinimg.com/originals/cc/47/a5/cc47a507854dfe4ea145ebb4c9ae51c4.jpg', startDay:"2020-02-20", endDate:'2020-03-20')
Film.create(tittle:'Blade runner 2049', synopsis:'En el año 2049 el oficial K, un nuevo replicante de la policía de Los Ángeles, emprende la búsqueda del replicante Rick Deckard, desaparecido 30 años antes. K piensa que en Deckard reside la clave que podría permitir salvar a la sociedad del caos en el que está inmersa.', image:'https://images-na.ssl-images-amazon.com/images/I/71PhjEaTZ6L._AC_SL1111_.jpg', startDay:"2020-02-25", endDate:'2020-03-25')
Film.create(tittle:'The Girl with the Dragon Tatto', synopsis:'Mikael Blomkvist, un desafortunado periodista financiero, encuentra la posibilidad de redimir su honor después de ser contratado por el rico industrialista sueco Henrik Vanger para resolver el asesinato de Harriet, la sobrina de Vanger, ocurrido hace 40 años. Vanger cree que Harriet fue asesinada por un miembro de su propia familia. Lisbeth Salander, una investigadora inusual, pero ingeniosa, se une a la búsqueda de la verdad de Blomkvist.', image:'https://upload.wikimedia.org/wikipedia/en/8/80/The_Girl_with_the_Dragon_Tattoo_Poster.jpg', startDay:"2020-02-29", endDate:'2020-03-30')
Film.create(tittle:'Inception', synopsis:'Dom Cobb es un ladrón con una extraña habilidad para entrar a los sueños de la gente y robarles los secretos de sus subconscientes. Su habilidad lo ha vuelto muy popular en el mundo del espionaje corporativo, pero ha tenido un gran costo en la gente que ama. Cobb obtiene la oportunidad de redimirse cuando recibe una tarea imposible: plantar una idea en la mente de una persona. Si tiene éxito, será el crimen perfecto, pero un enemigo se anticipa a sus movimientos.', image:'https://images-na.ssl-images-amazon.com/images/I/51Qx9c4ppzL._AC_.jpg', startDay:'2020-03-05', endDate:'2020-04-05')
Film.create(tittle:'Léon The Professional', synopsis:'Mathilda es una niña que no se lleva bien con su familia, excepto con su hermano pequeño. Su padre es un narcotraficante que hace negocios con Stan, un corrupto agente de la D.E.A. Un día Stan mata a su familia y Mathilda se refugia en casa de Léon, un solitario y misterioso vecino que resulta ser un asesino a sueldo, pero hará un pacto con él: ella se encargará de las tareas domésticas y le enseñará a leer a Léon y éste le enseñará a disparar para poder vengarse de la muerte de su hermano.', image:'https://i2.wp.com/www.plantandolibros.com/wp-content/uploads/2017/09/The-Professional-poster.jpg?resize=350%2C450', startDay:'2020-03-10', endDate:'2020-04-10')
Film.create(tittle:'Star Wars Episode III', synopsis:'Seducido por el lado oscuro, Anakin Skywalker se rebela contra su mentor, Obi-Wan Kenobi, y se convierte en Darth Vader.', image:'https://i.ebayimg.com/images/g/jN0AAOSwaRBcW3Q3/s-l400.jpg', startDay:'2020-03-15', endDate:'2020-04-15')
Film.create(tittle:'Eternal Sunshine of the Spotless Mind', synopsis:'Parecían la pareja ideal, su primer encuentro fue mágico, pero con el paso del tiempo ella deseó nunca haberlo conocido. Su anhelo se hace realidad gracias a un polémico y radical invento. Sin embargo descubrirán que el destino no se puede controlar.', image:'https://wallpapercave.com/wp/wp2392731.jpg', startDay:'2020-03-20', endDate:'2020-04-20')
Film.create(tittle:'The Amazing Spider-man', synopsis:'La investigación de Peter Parker para resolver la desaparición de sus padres lo coloca en el camino de un choque con el alter ego mortal de un científico conocido como el Lagarto.', image:'https://es.web.img3.acsta.net/medias/nmedia/18/84/50/16/20084857.jpg', startDay:'2020-03-30', endDate:'2020-05-30')


Booking.create("film_id": 8, "day": "2020-03-18", "cedula": "1039876239", "nombre": "Carlos Antonio Marin", "correo": "Carlos125@gmail.com", "celular": "3208760938");
Booking.create("film_id": 5, "day": "2020-03-13", "cedula": "1039876239", "nombre": "Andrea Montoya IVV", "correo": "andreamon@gmail.com", "celular": "3208760938");
